[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "diweir"
version = "0.0.1"
description = "A tool for DataOps on a RDBMS systems."
requires-python = ">=3.8"

dependencies = [
    "appdirs==1.4.4",
    "fastapi==0.111.0",
    "requests==2.31.0",
    "uvicorn==0.30.1",
    "SQLAlchemy==2.0.25",
    "pandas==2.1.4",
    "deg==1.0.1",
    "werkzeug==2.2.3"
]

authors = [
  { name="Supratik Chatterjee", email="supratikdevm96@gmail.com" },
]

maintainers = [
    { name="Supratik Chatterjee", email="supratikdevm96@gmail.com" },
]

license = {file = "LICENSE"}
readme = {file="README.md", content-type = "text/markdown"}
keywords = ["data", "anonymize", "obfuscate", "migrate", "backup", "archive", "purge", "rdbms", "oracle", "postgres"]

classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Developers",
    "Framework :: FastAPI",
    "Development Status :: 4 - Beta",
    "Topic :: Database",
    "Topic :: System :: Monitoring",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities"
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
diweir = "diweir:run"

[project.urls]
Homepage = "https://github.com/supratikchatterjee16/diweir"
Issues = "https://github.com/supratikchatterjee16/diweir/issues"